In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data1 = pd.read_excel("online_retail_II.xlsx",sheet_name="Year 2009-2010")
data2 = pd.read_excel("online_retail_II.xlsx",sheet_name="Year 2010-2011")
data = pd.concat([data1,data2],ignore_index=True)

In [ ]:
data.to_excel("Total_cleaning_onlinedata.xlsx",index=False)
print("Done")

In [3]:
print(data.shape)
print(data1.shape)
print(data2.shape)

(1067371, 8)
(525461, 8)
(541910, 8)

In [5]:
print(data.info())
print(data.columns)

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[us]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 65.1+ MB
None
Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='str')

In [4]:
data.columns = data.columns.str.strip().str.lower().str.replace(" ","_")
print(data.columns)

Index(['invoice', 'stockcode', 'description', 'quantity', 'invoicedate',
       'price', 'customer_id', 'country'],
      dtype='str')

In [5]:
data.duplicated().sum()

np.int64(34335)

In [6]:
data.drop_duplicates(inplace=True)
data.duplicated().sum()

np.int64(0)

In [9]:
data.isnull().any()

invoice        False
stockcode      False
description     True
quantity       False
invoicedate    False
price          False
customer_id     True
country        False
dtype: bool

In [ ]:
data["customer_id"].isnull().sum()

In [7]:
data.dtypes

invoice                object
stockcode              object
description            object
quantity                int64
invoicedate    datetime64[us]
price                 float64
customer_id           float64
country                   str
dtype: object

In [8]:
data["invoice"] = data["invoice"].astype(str).str.replace("c","C")
data_c = data[data["invoice"].str.startswith("C")]

In [9]:
data_c.shape

(19104, 8)

In [ ]:
data_c.to_excel("Cancellations_data.xlsx",index=False)

In [10]:
data = data[~data['invoice'].str.startswith(('C', 'c'))]

In [11]:
data.shape

(1013932, 8)

In [12]:
data["stockcode"] = data["stockcode"].astype(str).str.lower().str.strip()

In [13]:
data.dtypes

invoice                   str
stockcode                 str
description            object
quantity                int64
invoicedate    datetime64[us]
price                 float64
customer_id           float64
country                   str
dtype: object

In [14]:
sum(data["description"].isnull())

4275

In [15]:
data = data[
    ~((data['quantity'] <= 0) &
    (data['price'] <= 0))
]

In [16]:
data[
    (data['quantity'] <= 0) &
    (data['price'] <= 0)
]

Empty DataFrame
Columns: [invoice, stockcode, description, quantity, invoicedate, price, customer_id, country]
Index: []

In [20]:
data.isnull().any()

invoice        False
stockcode      False
description     True
quantity       False
invoicedate    False
price          False
customer_id     True
country        False
dtype: bool

In [17]:
print(data[data["quantity"]<=0])

Empty DataFrame
Columns: [invoice, stockcode, description, quantity, invoicedate, price, customer_id, country]
Index: []

In [18]:
print(data[data["price"]<=0])

        invoice stockcode                   description  quantity  \
3161     489659     21350                           NaN       230
3731     489781     84292                           NaN        17
4674     489825     22076            6 RIBBONS EMPIRE          12
5904     489861       dot                DOTCOM POSTAGE         1
6378     489882    35751c                           NaN        12
...         ...       ...                           ...       ...
1060795  581211     22142                         check        14
1062442  581234     72817                           NaN        27
1063965  581406    46000m  POLYESTER FILLER PAD 45x45cm       240
1063966  581406    46000s  POLYESTER FILLER PAD 40x40cm       300
1064015  581408     85175                           NaN        20

                invoicedate  price  customer_id         country
3161    2009-12-01 17:39:00    0.0          NaN  United Kingdom
3731    2009-12-02 11:45:00    0.0          NaN  United Kingdom
4674    2009-12-02 13:34:00    0.0      16126.0  United Kingdom
5904    2009-12-02 14:50:00    0.0          NaN  United Kingdom
6378    2009-12-02 16:22:00    0.0          NaN  United Kingdom
...                     ...    ...          ...             ...
1060795 2011-12-07 18:36:00    0.0          NaN  United Kingdom
1062442 2011-12-08 10:33:00    0.0          NaN  United Kingdom
1063965 2011-12-08 13:58:00    0.0          NaN  United Kingdom
1063966 2011-12-08 13:58:00    0.0          NaN  United Kingdom
1064015 2011-12-08 14:06:00    0.0          NaN  United Kingdom

[2626 rows x 8 columns]

In [19]:
data[
      ((data["price"]<=0)&
      (data["description"].isnull()))
]

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
6378,489882,35751c,NaN,12,2009-12-02 16:22:00,0.0,NaN,United Kingdom
6555,489898,79323g,NaN,954,2009-12-03 09:40:00,0.0,NaN,United Kingdom
6581,489903,21166,NaN,48,2009-12-03 09:57:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
1059173,581103,22689,NaN,4,2011-12-07 11:58:00,0.0,NaN,United Kingdom
1060787,581203,23406,NaN,15,2011-12-07 18:31:00,0.0,NaN,United Kingdom
1060793,581209,21620,NaN,6,2011-12-07 18:35:00,0.0,NaN,United Kingdom
1062442,581234,72817,NaN,27,2011-12-08 10:33:00,0.0,NaN,United Kingdom
1064015,581408,85175,NaN,20,2011-12-08 14:06:00,0.0,NaN,United Kingdom

In [20]:
data =data[
      ~((data["price"]<=0)&
      (data["description"].isnull()))
]

In [21]:
data[
      ((data["price"]<=0)&
      (data["description"].isnull()))
]

Empty DataFrame
Columns: [invoice, stockcode, description, quantity, invoicedate, price, customer_id, country]
Index: []

In [22]:
data["description"].isnull().sum()

np.int64(0)

In [23]:
(data["quantity"]<=0).sum()

np.int64(0)

In [24]:
(data["price"]<0).sum()

np.int64(5)

In [25]:
data[data["price"]<0]

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country
179403,A506401,b,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
276274,A516228,b,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
403472,A528059,b,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom
825444,A563186,b,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
825445,A563187,b,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [26]:
data = data[
    ~(data["price"]<0)
]

In [27]:
(data["price"]==0).sum()

np.int64(979)

In [ ]:
zero_price_desc = data[data['price'] == 0]['description'].value_counts()
print(zero_price_desc)

description
check                                  39
found                                  28
OWL DOORSTOP                           14
adjustment                             14
POLYESTER FILLER PAD 45x45cm           12
POLYESTER FILLER PAD 40x40cm           10
?                                       9
Found                                   9
FRENCH BLUE METAL DOOR SIGN 1           9
PICNIC BASKET WICKER LARGE              8
BOX OF 24 COCKTAIL PARASOLS             8
RED KITCHEN SCALES                      8
IVORY KITCHEN SCALES                    8
RECIPE BOX PANTRY YELLOW DESIGN         8
amazon                                  8
FRENCH BLUE METAL DOOR SIGN 8           8
Manual                                  7
WATERING CAN BLUE ELEPHANT              7
CHILDS GARDEN SPADE BLUE                7
ENAMEL WASH BOWL CREAM                  7
AIRLINE BAG VINTAGE WORLD CHAMPION      7
MINT KITCHEN SCALES                     7
RED RETROSPOT CHARLOTTE BAG             7
FRENCH BLUE METAL DOOR SIGN 4           7
FRENCH BLUE METAL DOOR SIGN No          7
FRENCH BLUE METAL DOOR SIGN 3           7
Amazon                                  7
FLAG OF ST GEORGE CAR FLAG              6
GLASS JAR DIGESTIVE BISCUITS            6
CHILLI LIGHTS                           6
AIRLINE BAG VINTAGE TOKYO 78            6
CHILDRENS GARDEN GLOVES BLUE            6
mailout                                 6
ENAMEL FIRE BUCKET CREAM                6
ENAMEL WATERING CAN CREAM               6
ENAMEL FLOWER JUG CREAM                 6
DOORMAT WELCOME TO OUR HOME             6
RECIPE BOX BLUE SKETCHBOOK DESIGN       6
FRENCH BLUE METAL DOOR SIGN 7           6
FRENCH BLUE METAL DOOR SIGN 5           6
FRENCH BLUE METAL DOOR SIGN 6           6
DOTCOM POSTAGE                          5
SMALL POPCORN HOLDER                    5
CHILDS GARDEN BRUSH PINK                5
GLASS JAR DAISY FRESH COTTON WOOL       5
ROUND SNACK BOXES SET OF 4 SKULLS       5
HEART OF WICKER SMALL                   5
HEART OF WICKER LARGE                   5
GLASS JAR PEACOCK BATH SALTS            5
GLASS JAR ENGLISH CONFECTIONERY         5
PICNIC BASKET WICKER SMALL              5
WHITE HANGING HEART T-LIGHT HOLDER      5
STRAWBERRY FAIRY CAKE TEAPOT            5
GLASS JAR KINGS CHOICE                  5
KINGS CHOICE BISCUIT TIN                5
FRENCH BLUE METAL DOOR SIGN 0           5
FRENCH BLUE METAL DOOR SIGN 9           5
FRENCH BLUE METAL DOOR SIGN 2           5
had been put aside                      5
DOOR MAT UNION JACK GUNS AND ROSES      4
temp                                    4
MILK PAN PINK RETROSPOT                 4
RED RETROSPOT STORAGE JAR               4
HANGING METAL STAR LANTERN              4
CHILDS GARDEN BRUSH BLUE                4
WATERING CAN PINK BUNNY                 4
REGENCY CAKESTAND 3 TIER                4
CHARLOTTE BAG SUKI DESIGN               4
GLASS JAR MARMALADE                     4
ZINC WILLIE WINKIE  CANDLE STICK        4
DOORMAT NEIGHBOURHOOD WITCH             4
DOORMAT AIRMAIL                         4
RED RETROSPOT CHILDRENS UMBRELLA        4
JUMBO BAG RED RETROSPOT                 4
DOORMAT ENGLISH ROSE                    4
SET OF 6 SOLDIER SKITTLES               4
BLACK KITCHEN SCALES                    4
dotcom                                  4
RETRO SPOT LARGE MILK JUG               3
DOOR MAT FANCY FONT HOME SWEET HOME     3
RED RETROSPOT SUGAR JAM BOWL            3
JUMBO BAG TOYS                          3
HANGING METAL HEART LANTERN             3
DOOR MAT AIRMAIL                        3
SEASIDE FLYING DISC                     3
RETRO "TEA FOR ONE"                     3
RED RETROSPOT BUTTER DISH               3
FLAG OF ST GEORGE CHAIR                 3
PORCELAIN BUTTERFLY OIL BURNER          3
GROW YOUR OWN PLANT IN A CAN            3
ENAMEL MEASURING JUG CREAM              3
checked                                 3
TEATIME FUNKY FLOWER BACKPACK FOR 2     3
CERAMIC STRAWBERRY CAKE MONEY BANK      3
STRAWBERRY LUNCH BOX WITH CUTLERY       3
TRADITIONAL WOODEN SKIPPING ROPE        3
VINTAGE HEADS AND TAILS CARD GAME       3
CHILDRENS APRON SPACEBOY DESIGN         3
WOODLAND CHARLOTTE BAG                  3
CREAM SWEETHEART MINI CHEST             3
damaged                                 3
BINGO SET                               3
GREEN REGENCY TEACUP AND SAUCER         3
CHARLOTTE BAG PINK POLKADOT             3
CHILDS GARDEN TROWEL BLUE               3
AIRLINE BAG VINTAGE JET SET BROWN       3
ILLUSTRATED CAT BOWL                    3
HOLIDAY FUN LUDO                        3
AIRLINE BAG VINTAGE JET SET RED         3
DOORMAT RESPECTABLE HOUSE               3
JUMBO BAG STRAWBERRY                    3
CHILDS GARDEN SPADE PINK                3
COFFEE MUG CAT + BIRD DESIGN            3
AMAZON                                  3
CHRISTMAS PUDDING TRINKET POT           2
ANTIQUE LILY FAIRY LIGHTS               2
CHARLOTTE BAG , SUKI DESIGN             2
This is a test product.                 2
MILK PAN RED RETROSPOT                  2
DOOR MAT BIRD ON THE WIRE               2
DOOR MAT FRIENDSHIP                     2
DOOR MAT HEARTS                         2
AIRLINE BAG VINTAGE JET SET WHITE       2
FRYING PAN PINK POLKADOT                2
DOORSTOP FOOTBALL DESIGN                2
LUNCH BAG PINK RETROSPOT                2
CHILDRENS GARDEN GLOVES PINK            2
UNION STRIPE WITH FRINGE  HAMMOCK       2
KEY FOB , SHED                          2
update                                  2
CHARLOTTE BAG PINK WITH WHITE SPOTS     2
BLUE RETRO BAR STOOL                    2
RED RETRO BAR STOOL                     2
LUNCH BAG WOODLAND                      2
ENAMEL BREAD BIN CREAM                  2
MAGIC DRAWING SLATE SPACEBOY            2
SET OF 9 BLACK SKULL BALLOONS           2
WORLD WAR 2 GLIDERS ASSTD DESIGNS       2
FAIRY CAKES NOTEBOOK A6 SIZE            2
DOORMAT HOME SWEET HOME BLUE            2
TROPICAL LUGGAGE TAG                    2
TROPICAL PASSPORT COVER                 2
ENAMEL COLANDER CREAM                   2
DOORMAT FANCY FONT HOME SWEET HOME      2
TV DINNER TRAY DOLLY GIRL               2
ROUND SNACK BOXES SET OF4 WOODLAND      2
amendment                               2
DOG BOWL CHASING BALL DESIGN            2
PARTY BUNTING                           2
VICTORIAN SEWING BOX LARGE              2
DOORMAT HEARTS                          2
DOORSTOP RACING CAR DESIGN              2
RED GINGHAM TEDDY BEAR                  2
TOY TIDY SPACEBOY                       2
amazon adjustment                       2
Mailout                                 2
TRAVEL SEWING KIT                       2
TV DINNER TRAY VINTAGE PAISLEY          2
SPACEBOY TV DINNER TRAY                 2
VINTAGE SNAKES & LADDERS                2
BLUE POLKADOT LUGGAGE TAG               2
BLUE POLKADOT PASSPORT COVER            2
SET OF 16 VINTAGE BLACK CUTLERY         2
BISCUIT TIN VINTAGE GREEN               2
WHEELBARROW FOR CHILDREN                2
SKULL DESIGN TV DINNER TRAY             2
Adjustment                              2
CERAMIC STRAWBERRY MONEY BOX            2
returned                                2
JUMBO BAG SPACEBOY DESIGN               2
SPOTTY BUNTING                          2
test                                    2
taig adjust                             2
6 RIBBONS EMPIRE                        1
DOOR MAT FAIRY CAKE                     1
CHRISTMAS CRAFT WHITE FAIRY             1
ANTIQUE GLASS HEART DECORATION          1
 FLAMINGO LIGHTS                        1
WOODLAND  STICKERS                      1
CUBIC MUG TEATIME CAKES                 1
VINTAGE GLASS COFFEE CADDY              1
WOODEN REGATTA BUNTING                  1
WOODEN UNION JACK BUNTING               1
PINK  SPOTTY PLATE                      1
ASSORTED COLOUR BIRD ORNAMENT           1
LUNCH BAG SPACEBOY DESIGN               1
RETRO SPOTS BUTTER DISH                 1
FRYING PAN RED POLKADOT                 1
JUMBO BAG RED WHITE SPOTTY              1
JUMBO SHOPPER VINTAGE RED PAISLEY       1
LUNCHBOX WITH CUTLERY RETROSPOT         1
DOOR MAT 3 SMILEY CATS                  1
FLAG OF ST GEORGE                       1
CAST IRON HOOK GARDEN TROWEL            1
CAST IRON HOOK GARDEN FORK              1
HEART EAR MUFF HEADPHONES               1
MAGNETS PACK OF 4 SWALLOWS              1
MAGNETS PACK OF 4 CHILDHOOD MEMORY      1
found again                             1
POLYESTER FILLER PAD 65CMx65CM          1
DOOR MAT SPOTTY HOME SWEET HOME         1
DOOR MAT RED SPOT                       1
DOOR MAT WELCOME PUPPIES                1
DOOR MAT ENGLISH ROSE                   1
DOOR MAT BLACK FLOCK                    1
DOOR MAT UNION FLAG                     1
wrong invc                              1
DOOR MAT TOPIARY                        1
CHARLOTTE BAG , PINK/WHITE SPOTS        1
ROUND SNACK BOXES SET OF 4 FRUITS       1
RED RETROSPOT PUDDING BOWL              1
RED RETROSPOT SMALL MILK JUG            1
HANGING METAL BIRD BATH                 1
Rust fixed                              1
SET/5 RED SPOTTY LID GLASS BOWLS        1
WOODEN SCHOOL COLOURING SET             1
FRYING PAN BLUE POLKADOT                1
DAIRY MAID LARGE MILK JUG               1
DAIRY MAID TOASTRACK                    1
CORONA MEXICAN TRAY                     1
GROW YOUR OWN BASIL IN ENAMEL MUG       1
DOOR MAT NEIGHBOURHOOD WITCH            1
DOOR MAT RESPECTABLE HOUSE              1
POLYESTER FILLER PAD 30CMx30CM          1
EIGHT PIECE DINOSAUR SET                1
DINOSAUR PARTY BAG + STICKER SET        1
BROCADE RING PURSE                      1
PACK OF 12 TRADITIONAL CRAYONS          1
FAIRY CAKES NOTEBOOK A7 SIZE            1
WOODLAND PARTY BAG + STICKER SET        1
12 COLOURED PARTY BALLOONS              1
FEATHER PEN,HOT PINK                    1
FEATHER PEN,COAL BLACK                  1
ASSORTED COLOURS SILK FAN               1
RED SPOTS  WRAP                         1
MAGIC DRAWING SLATE PURDEY              1
MAGIC DRAWING SLATE BUNNIES             1
MAGIC DRAWING SLATE DINOSAUR            1
REX CASH+CARRY JUMBO SHOPPER            1
12 PENCILS SMALL TUBE SKULL             1
12 PENCILS SMALL TUBE RED SPOTTY        1
FUNKY GIRLZ ASST MAGNETIC MEMO PAD      1
correct previous adjustment             1
22719                                   1
tk maxx mix up with pink                1
RED SPOTTY CHARLOTTE BAG                1
DOORMAT UNION FLAG                      1
DOORMAT MULTICOLOUR STRIPE              1
WOODEN CROQUET GARDEN SET               1
DOORSTOP RUSSIAN DOLL RETROSPOT         1
LUNCH BOX WITH CUTLERY RETROSPOT        1
DOORMAT SPOTTY HOME SWEET HOME          1
BLACK RETRO BAR STOOL                   1
FUSCHIA RETRO BAR STOOL                 1
DOORMAT FRIENDSHIP                      1
PIN CUSHION RUSSIAN DOLL PINK           1
SILK PURSE RUSSIAN DOLL PINK            1
LOVE HEART TRINKET POT                  1
S/6 WOODEN SKITTLES IN COTTON BAG       1
DOORMAT RED SPOT                        1
RED SPOTTY BOWL                         1
PINK SPOTTY BOWL                        1
RETROSPOT BABUSHKA DOORSTOP             1
debenhams                               1
Sold as A/B                             1
POLYESTER FILLER PAD 45x30cm            1
dotcom email                            1
eurobargain invc/credit                 1
CAKE STAND LACE WHITE                   1
JUMBO STORAGE BAG SUKI                  1
200 RED + WHITE BENDY STRAWS            1
DOORMAT WELCOME SUNRISE                 1
CHROME EURO HOOK 20cm                   1
SILVER MINI TAPE MEASURE                1
DOLLY GIRL LUNCH BOX                    1
NOEL WOODEN BLOCK LETTERS               1
LIPSTICK PEN FUSCHIA                    1
CHRISTMAS CARD STACK OF PRESENTS        1
CHRISTMAS CARD SCREEN PRINT             1
RED RETROSPOT CAKE STAND                1
?sold individually?                     1
BREAD BIN DINER STYLE RED               1
VINTAGE CREAM CAT FOOD CONTAINER        1
SCANDINAVIAN REDS RIBBONS               1
mailout addition                        1
ROUND CAKE TIN VINTAGE GREEN            1
CREAM SWEETHEART LETTER RACK            1
DOORMAT 3 SMILEY CATS                   1
EMPIRE UNION JACK TV DINNER TRAY        1
CHILDS GARDEN RAKE BLUE                 1
4 TRADITIONAL SPINNING TOPS             1
FULL ENGLISH BREAKFAST PLATE            1
LUNCH BOX WITH CUTLERY FAIRY CAKES      1
MILK PAN PINK POLKADOT                  1
STRAWBERRY CERAMIC TRINKET BOX          1
PACK OF 6 BIRDY GIFT TAGS               1
amazon sales                            1
WHITE SKULL HOT WATER BOTTLE            1
CHOCOLATE HOT WATER BOTTLE              1
ADVENT CALENDAR GINGHAM SACK            1
HOT WATER BOTTLE TEA AND SYMPATHY       1
SET/20 RED RETROSPOT PAPER NAPKINS      1
FAWN BLUE HOT WATER BOTTLE              1
BISCUIT TIN VINTAGE RED                 1
CERAMIC PIRATE CHEST MONEY BANK         1
CERAMIC LOVE HEART MONEY BANK           1
RED RETROSPOT TEA CUP AND SAUCER        1
PAPER BUNTING RETROSPOT                 1
PLASTERS IN TIN SKULLS                  1
BLUE SPOT CERAMIC DRAWER KNOB           1
WHITE SPOT BLUE CERAMIC DRAWER KNOB     1
ORGANISER WOOD ANTIQUE WHITE            1
COFFEE MUG DOG + BALL DESIGN            1
PINK DOUGHNUT TRINKET POT               1
DOORMAT RED RETROSPOT                   1
LUNCH BAG SUKI DESIGN                   1
KEY FOB , GARAGE DESIGN                 1
ROSES REGENCY TEACUP AND SAUCER         1
PINK REGENCY TEACUP AND SAUCER          1
DOORMAT MERRY CHRISTMAS RED             1
wrongly sold (22719) barcode            1
BOX OF VINTAGE JIGSAW BLOCKS            1
CHILDS GARDEN TROWEL PINK               1
CIRCUS PARADE LUNCH BOX                 1
CERAMIC BOWL WITH LOVE HEART DESIGN     1
rcvd be air temp fix for dotcom sit     1
MINI CAKE STAND  HANGING STRAWBERY      1
HEART GARLAND RUSTIC PADDED             1
CHICK GREY HOT WATER BOTTLE             1
CHILDS BREAKFAST SET CIRCUS PARADE      1
did  a credit  and did not tick ret     1
mailout                                 1
BLACK MINI TAPE MEASURE                 1
BAKING SET SPACEBOY DESIGN              1
ASSTD MULTICOLOUR CIRCLES MUG           1
SET OF 20 KIDS COOKIE CUTTERS           1
BOX OF 6 ASSORTED COLOUR TEASPOONS      1
on cargo order                          1
CERAMIC CHERRY CAKE MONEY BANK          1
CERAMIC HEART FAIRY CAKE MONEY BANK     1
PIGGY BANK RETROSPOT                    1
WOODEN BOX OF DOMINOES                  1
FRYING PAN BLUE POLKADOT                1
CHILDS GARDEN FORK PINK                 1
CHILDS GARDEN FORK BLUE                 1
incorrectly credited C550456 see 47     1
to push order througha s stock was      1
FOUND                                   1
TRAVEL CARD WALLET DOTCOMGIFTSHOP       1
PACK OF 12 LONDON TISSUES               1
came coded as 20713                     1
alan hodge cant mamage this section     1
VINTAGE LEAF MAGNETIC NOTEPAD           1
FBA                                     1
 OVAL WALL MIRROR DIAMANTE              1
JAM MAKING SET WITH JARS                1
SET OF 6 NATIVITY MAGNETS               1
PARTY METAL SIGN                        1
GARAGE KEY FOB                          1
KEY FOB , BACK DOOR                     1
DINOSAUR LUNCH BOX WITH CUTLERY         1
TOADSTOOL MONEY BOX                     1
SET OF 2 CERAMIC PAINTED HEARTS         1
SET OF 2 CERAMIC CHRISTMAS REINDEER     1
36 FOIL STAR CAKE CASES                 1
POLKADOT RAIN HAT                       1
allocate stock for dotcom orders ta     1
add stock to allocate online orders     1
for online retail orders                1
found box                               1
Found in w/hse                          1
website fixed                           1
PADS TO MATCH ALL CUSHIONS              1
Lighthouse Trading zero invc incorr     1
michel oops                             1
GLASS CLOCHE SMALL                      1
wrongly coded 20713                     1
Had been put aside.                     1
Sale error                              1
Amazon Adjustment                       1
wrongly marked 23343                    1
Marked as 23343                         1
PASTEL COLOUR HONEYCOMB FAN             1
wrongly coded 23343                     1
Found by jackie                         1
wrongly marked                          1
BISCUIT TIN VINTAGE CHRISTMAS           1
CHILDREN'S APRON DOLLY GIRL             1
MINI LIGHTS WOODLAND MUSHROOMS          1
PAPER BUNTING VINTAGE PAISLEY           1
amazon adjust                           1
dotcomstock                             1
John Lewis                              1
SET OF 2 TRAYS HOME SWEET HOME          1
dotcom adjust                           1
check?                                  1
ASSTD DESIGN 3D PAPER STICKERS          1
FRIDGE MAGNETS LES ENFANTS ASSORTED     1
CLASSIC GLASS COOKIE JAR                1
Name: count, dtype: int64

In [28]:
data = data [
    ~(data["price"]<=0)
]

In [29]:
data[data["price"]<=0]

Empty DataFrame
Columns: [invoice, stockcode, description, quantity, invoicedate, price, customer_id, country]
Index: []

In [30]:
data.isnull().any()

invoice        False
stockcode      False
description    False
quantity       False
invoicedate    False
price          False
customer_id     True
country        False
dtype: bool

In [31]:
(data["description"].isnull()).sum()

np.int64(0)

In [32]:
(data["price"]<=0).sum()

np.int64(0)

In [33]:
(data["quantity"]<=0).sum()

np.int64(0)

In [34]:
data.dtypes

invoice                   str
stockcode                 str
description            object
quantity                int64
invoicedate    datetime64[us]
price                 float64
customer_id           float64
country                   str
dtype: object

In [35]:
data["description"]= data["description"].str.strip().str.lower()

In [36]:
data.groupby('stockcode')['description'].nunique().sort_values(ascending=False).head(20)

stockcode
22345     4
22346     4
20685     4
22344     4
22384     4
23196     4
23236     4
21955     3
22852     3
22191     3
22937     3
22853     3
22356     3
22536     3
17107d    3
22844     3
21243     3
22197     3
22343     3
23126     3
Name: description, dtype: int64

In [37]:
multiple_desc = (
    data.groupby('stockcode')['description']
      .unique()
)

print(multiple_desc[multiple_desc.apply(len) > 1])

stockcode
15058a    [blue white spots garden parasol, blue polkado...
15058b    [pink white spots garden parasol, pink polkado...
16012     [food/drink spunge stickers, food/drink sponge...
16151a    [flower des blue handbag/orang handl, flowers ...
16156l                      [wrap, carousel, wrap carousel]
                                ...
90014a    [silver/mop orbit necklace, silver m.o.p. orbi...
90014b    [gold m pearl  orbit necklace, gold m.o.p. orb...
90014c    [silver/black orbit necklace, silver and black...
90208     [pair of enamel flower cluster slide, pair of ...
adjust    [adjustment by john on 26/01/2010 16, adjustme...
Name: description, Length: 600, dtype: object

In [38]:
lookup = (
    data.groupby('stockcode')['description']
      .agg(lambda x: x.value_counts().index[0])
      .reset_index()
)

In [39]:
data['description'] = data['stockcode'].map(
    lookup.set_index('stockcode')['description']
)

In [40]:
data.dtypes

invoice                   str
stockcode                 str
description               str
quantity                int64
invoicedate    datetime64[us]
price                 float64
customer_id           float64
country                   str
dtype: object

In [41]:
data["invoicedate"] = pd.to_datetime(data["invoicedate"])

In [42]:
data["invoicedate"].isnull().sum()

np.int64(0)

In [43]:
data.isnull().any()

invoice        False
stockcode      False
description    False
quantity       False
invoicedate    False
price          False
customer_id     True
country        False
dtype: bool

In [54]:
data.duplicated().sum()

np.int64(2)

In [ ]:
data.drop_duplicates()

In [44]:
data.dtypes

invoice                   str
stockcode                 str
description               str
quantity                int64
invoicedate    datetime64[us]
price                 float64
customer_id           float64
country                   str
dtype: object

In [46]:

data["description"].str.lower().str.strip()

non_product_keywords = ['bank charges', 'postage', 'manual', 'adjustment',"dotcom postage","adjustment by john on 26/01/2010 16","adjustment by john on 26/01/2010 17"]

data = data[~data['description'].isin(non_product_keywords)]

In [ ]:
data

In [48]:
countries =data["country"].value_counts().sort_index()

print(countries)

country
Australia                 1783
Austria                    888
Bahrain                    124
Belgium                   2911
Bermuda                     34
Brazil                      94
Canada                     227
Channel Islands           1550
Cyprus                    1132
Czech Republic              24
Denmark                    756
EIRE                     17112
European Community          57
Finland                    985
France                   13164
Germany                  15788
Greece                     653
Hong Kong                  347
Iceland                    222
Israel                     366
Italy                     1411
Japan                      468
Korea                       53
Lebanon                     57
Lithuania                  154
Malta                      277
Netherlands               4981
Nigeria                     29
Norway                    1263
Poland                     498
Portugal                  2409
RSA                        166
Saudi Arabia                 9
Singapore                  332
Spain                     3560
Sweden                    1285
Switzerland               3068
Thailand                    76
USA                        404
United Arab Emirates       462
United Kingdom          923745
Unspecified                748
West Indies                 54
Name: count, dtype: int64

In [49]:
data["country"] = data["country"].astype(str).str.strip()
data["country"] = data["country"].str.title()

In [50]:
print(data["country"].value_counts().sort_index())

country
Australia                 1783
Austria                    888
Bahrain                    124
Belgium                   2911
Bermuda                     34
Brazil                      94
Canada                     227
Channel Islands           1550
Cyprus                    1132
Czech Republic              24
Denmark                    756
Eire                     17112
European Community          57
Finland                    985
France                   13164
Germany                  15788
Greece                     653
Hong Kong                  347
Iceland                    222
Israel                     366
Italy                     1411
Japan                      468
Korea                       53
Lebanon                     57
Lithuania                  154
Malta                      277
Netherlands               4981
Nigeria                     29
Norway                    1263
Poland                     498
Portugal                  2409
Rsa                        166
Saudi Arabia                 9
Singapore                  332
Spain                     3560
Sweden                    1285
Switzerland               3068
Thailand                    76
United Arab Emirates       462
United Kingdom          923745
Unspecified                748
Usa                        404
West Indies                 54
Name: count, dtype: int64

In [ ]:
data.dtypes

In [51]:
data =data[data["country"]!="Unspecified"]

In [52]:
data["country"].value_counts().sort_index()

country
Australia                 1783
Austria                    888
Bahrain                    124
Belgium                   2911
Bermuda                     34
Brazil                      94
Canada                     227
Channel Islands           1550
Cyprus                    1132
Czech Republic              24
Denmark                    756
Eire                     17112
European Community          57
Finland                    985
France                   13164
Germany                  15788
Greece                     653
Hong Kong                  347
Iceland                    222
Israel                     366
Italy                     1411
Japan                      468
Korea                       53
Lebanon                     57
Lithuania                  154
Malta                      277
Netherlands               4981
Nigeria                     29
Norway                    1263
Poland                     498
Portugal                  2409
Rsa                        166
Saudi Arabia                 9
Singapore                  332
Spain                     3560
Sweden                    1285
Switzerland               3068
Thailand                    76
United Arab Emirates       462
United Kingdom          923745
Usa                        404
West Indies                 54
Name: count, dtype: int64

In [53]:
data.to_excel("NEW_Cleaning_onlinedata.xlsx",index=False)
print("Done")

Done